spring.application.name=assorttis
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/assorttis
spring.datasource.username=admin9
spring.datasource.password=admin9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.sql.init.mode=always



# #  testassorttis
# # Gmail SMTP Configuration
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=technologybri@gmail.com
# spring.mail.password=lbrltfnghbhvkiqj
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true
