spring.application.name=assorttis
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/assortiss
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.sql.init.mode=always

project-references.templates-path=./templates
project-references.missing-value=N/A


