spring.application.name=assorttis
server.port=${SERVER_PORT:8082}



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:testassorttis}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:admin9}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:admin9}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.sql.init.mode=always

project-references.templates-path=./templates
project-references.missing-value=N/A


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hajerboukhari2018@gmail.com
spring.mail.password=kaso yxzf btew qkny
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


